
version: '3.8'

services:
  web:
    image: kidplay-hub:latest
    # Nếu bạn push lên registry, hãy đổi thành: your-registry.com/kidplay-hub:latest
    ports:
      - "80:80"
    environment:
      - API_KEY=${API_KEY}
    deploy:
      replicas: 3
      update_config:
        parallelism: 1
        delay: 10s
        order: start-first
      restart_policy:
        condition: on-failure
        max_attempts: 3
        window: 120s
      placement:
        constraints:
          - node.role == worker
    networks:
      - kidplay-net

networks:
  kidplay-net:
    driver: overlay
